import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Main from "../components/homepage/main/main";
import About from "../components/homepage/about/about";
import Work from "../components/homepage/work/work";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Joseph Baquerizo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Main />
        <About />
        <Work />
      </main>
      
    </div>
  )
}
